### ISSUE TITLE
just init-dev open:  root.crt: No such file or directory

### ISSUE THREAD

**Issue by gedw99** [PixyBlue/lazy-lob-web#2]
just following the readme instruction.

docker stuff working fine...

```sh
just build boot 
```

then 2nd things fails with the following after putting in my host password.

```sh

just init-dev open
docker compose exec web npm install

changed 1 package, and audited 16 packages in 611ms

found 0 vulnerabilities
docker compose exec web dbmate up
just migrate
just command web migrate
docker compose exec web migrate
sudo trust anchor ./app/data/web/pki/authorities/local/root.crt
Password:
p11-kit: couldn't open and map file: ./app/data/web/pki/authorities/local/root.crt: No such file or directory
p11-kit: failed to parse file: ./app/data/web/pki/authorities/local/root.crt
error: Recipe `init-dev` failed on line 12 with exit code 1

**Comment by taophp** [comment]
There is two issues here:
1. the path to the crt files is wrong, you worked around it and the PR #3 will fix it (and close the issue);
2. the way certificates are installed on the host OS.

As I do not own any Mac (and don't want it), I can hardly reproduce and fix it myself. So you may fix it yourself and make a PR, it you want. Or open an other issue and hope someone will some day... In the last case, I'll certainly update the Readme to point the problem and explain.

The fact is that's not a critical issue. Certificates are only needed to avoided boring browser warnings about  untrusted localhost certificates and add security exceptions each time you open the project again. If you can live with them, then you could make the stuff working by replacing the `init-dev` command by a simple `init`:
```
just init open
```

Let me know what you think.

**Comment by taophp** [comment]
BTW, GPT suggested to use this command instead of trust anchor:
```
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ./data/web/pki/authorities/local/root.crt
```
Hope it helps !

**Comment by taophp** [comment]
Maybe I miss something, but:
> Note that automatically installing the certificate into the local trust stores is for convenience only and isn't guaranteed to work, especially _**if containers are being used**_ or if Caddy is being run as an unprivileged system service.

As Caddy runs in a docker, I don't know how to make it automatically install its certificate on the host (and it is the same using the `caddy trust` command inside the container).

**Comment by taophp** [comment]
Seems good !

**Comment by taophp** [comment]
Do you want to do it ? After all, you are best placed to do this as you are the one who discovered both the problem and its solution.
